---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA+69G0ectBhTBdpstVoMfW9hH9mAxwcWnaT7z3IVaZZjsjL/hq2hfrsbGAXzzMoBtfpkbPlVhbhK1bwTUKEbTpgeuShU+Up+Y+gxzZAEWFYiV1S+lE0xWkcKV7EV3YvAa5cxrit9CmvI6A5BJXGIKsLPwh+KsArkUew5HrUYYj4YQP3XKg6/76xrSFFxwxZzl8mANkMIS7u6rqOdOzXzwttzUu2a6jMXnB8GIUq9RzKI7hSEU6T6v3laKYSsJHIc1/5pFJdNkZ+fnTh7Dn8hrKJwpumBSFpIrzh6E7z/6I1EjAjnJYB0ptNGsFgZUanzkjosUl3ZfiobaYxcCZgDHc9K+K1K/gx31bZVWLIDVZ/4d8oGulYJaGJQHWZmt6/p9mTgTPW+b000mljy34z1Tr/oksfm9INW0pIiwI7d0J+ImP4izN09YkD/YKfTmdoxW+/dTFdzWK2P5MT30jzkCUui/IsCRrUIt5nzPWVjIQyn8gU3fbx118JkgnQVuLw5pkZaKghT5lbSj7fvMx532oP5LFPOAry6NsoZCoocPpTioaTS5Oi/Zm6dIwritekVwpkWSStL2iIU/VZkernfdUgXroz5uIFw5zYXc2bjBSzA8Mgqc4lo6JXPChlVAcoLdFf2A8RxZCNCqCUTUDgQxeEmU+q3p8llsvxHv7hAL0kqvxqJDt2K1EgAGG32op7AoNquELbP+c
    admin-user: AgCGblSSNYX2c9NNshNCIC7yh5fWeD7wbQuuwSxb7AN7ieNTYb9aXqOOwf04783sgOYBIvxrPk+1RBADi8gUXeYU0LNVN8ny1lCTUF+KPI00TvFD/BL4fCdonPc2dJ1z6XTwXIWFNvw59T1sFGT14lyLHu49wnsE7re/BMMuPo+0QWDcRH0flJQbS2W+HH3ekuI4fjh/ahzZrw979WD86jWOc15yogp2Wm1USd/stABqlXi1kSSGEySP8fmyGYx2xkSKtm7jQJ3Gd15nEbsKqvJv40lsYqUG7runmhxbFT+XhMUJ7Dosr1syF1z2SDkvZSIM4Qu3xzCejjkAWKW+UlzjqOBCanaIZq4VV1h4lLl5v7dpoijJHLKSrCymlRnsZptdtGXSBtnVS7zbZ6ydU6XbaXAzefAZmER1m/Yi/2ihjRjCjfCZCgGg728xtF09bIRARnoVlVb/48FjDWgcUioBTxGQvwrT8Gw7hHcLfFoOQYkKBeqfSBWdILAtzhsoDSQmGKBv93DF2D0RxvxZZpAq+GeCk3E7IYZFxVg9PkwtMu0V2Uv+YuZgtSigPSoGwitHzsgur7N9vwmz2Tr6C8N/s4IlMAmdREUFVteg+D9FJ+OtEPEGdMr+91fNVVk2x4535q9QDu++2/87ULv/OhsV05D/Sef1jcIFgOATlKlkrgMW9fRDx4dAJjJjqKQ8ys0eF2IvgQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
